/* Standalone design prototype. All lesson content below is original illustrative copy. */
(() => {
  'use strict';
  const rows = [
    [0, 'Thinking clearly is a skill we can practice, not a talent we are born with.', '清晰思考是一种可以练习的技能，而不是与生俱来的天赋。'],
    [28, 'When information is abundant, attention becomes a deliberate choice.', '当信息无处不在时，把注意力放在哪里就成了一种主动选择。'],
    [55, 'A confident answer can still be built on a weak assumption.', '一个听起来很自信的答案，也可能建立在薄弱的假设之上。'],
    [70, 'Before asking for an answer, take a moment to define the question.', '在寻找答案之前，先花一点时间把问题说清楚。'],
    [78, 'What exactly are you trying to understand or decide?', '你究竟想理解什么，或者做出什么决定？'],
    [85, 'Write down the question in your own words, as simply as possible.', '用自己的话写下问题，越简单、越清楚越好。'],
    [92, 'Clear thinking starts with separating what you know from what you assume.', '清晰思考的第一步，是分清已知事实与自己的假设。'],
    [101, 'A fact can be checked. An assumption still needs to be tested.', '事实可以被核查，而假设仍然需要经过检验。'],
    [110, 'Put them in two columns, and notice where the evidence is missing.', '把它们分成两列，看看哪些地方还缺少证据。'],
    [119, 'For example, a popular idea is not necessarily a useful idea.', '比如，一个广受欢迎的想法，不一定是一个有用的想法。'],
    [128, 'Ask what would change your mind before you look for more support.', '在继续寻找支持之前，先问问什么证据会让你改变看法。'],
    [138, 'This small habit creates space between a reaction and a decision.', '这个小习惯，能让你在本能反应与最终决定之间留出思考空间。'],
    [180, 'A good question makes your uncertainty visible.', '一个好问题，能让你看见自己还不确定的地方。'],
    [240, 'Use AI to explore alternatives, not just to repeat your first idea.', '用 AI 探索其他可能性，而不只是重复你最初的想法。'],
    [310, 'Ask for the strongest argument against your preferred answer.', '请它提出反对你倾向答案的最有力论据。'],
    [420, 'Treat an AI answer as a starting point for inquiry.', '把 AI 的回答，当作进一步探究的起点。'],
    [505, 'Follow an important claim back to its original source.', '对于重要论断，沿着引用追溯到原始来源。'],
    [590, 'If you cannot verify a claim, keep the uncertainty in your notes.', '如果无法验证一项论断，就在笔记中保留它的不确定性。'],
    [670, 'Turn what you learned into a small experiment you can run this week.', '把学到的内容，转化为本周就能进行的小实验。'],
    [765, 'Write a prediction, take action, and compare the result.', '写下预测，采取行动，再把结果与预测进行对照。'],
    [880, 'Reflection helps you improve the way you think, not just the answer.', '复盘帮助你改善思考方式，而不只是修改答案。'],
    [975, 'Keep a short decision journal: evidence, assumptions, and the next step.', '写一份简短的决策日志：证据、假设，以及下一步。'],
    [1060, 'The goal is not certainty. The goal is a better way to learn.', '目标不是获得绝对确定性，而是找到更好的学习方式。'],
    [1110, 'Start with one question today, and give it your full attention.', '今天，就从一个问题开始，把注意力真正放在它身上。']
  ];
  const translations = {
    ja: ['明確に考える力は、生まれつきの才能ではなく、練習できるスキルです。','情報が豊富な時代には、注意をどこに向けるかを自分で選ぶ必要があります。','自信に満ちた答えでも、弱い仮定に基づいていることがあります。','答えを求める前に、まず問いを明確にしましょう。','何を理解し、何を決めようとしているのでしょうか。','できるだけ簡潔に、自分の言葉で問いを書いてみましょう。','明確に考える第一歩は、知っていることと仮定していることを分けることです。','事実は確認できます。仮定はまだ検証する必要があります。','二つの列に分け、どこに証拠が不足しているかを確認しましょう。','例えば、人気のあるアイデアが必ずしも役に立つとは限りません。','裏付けを探す前に、どのような証拠なら考えが変わるかを問いましょう。','この小さな習慣が、反応と決断の間に考える余地を生みます。','よい問いは、不確かな部分を明らかにします。','AI は最初のアイデアを繰り返すためではなく、別の可能性を探るために使いましょう。','自分が支持する答えへの最も強い反論を求めましょう。','AI の答えを、さらに調べるための出発点と考えましょう。','重要な主張は、元の情報源までたどりましょう。','確認できない主張は、不確かであることを記録しましょう。','学んだことを、今週できる小さな実験に変えましょう。','予測を書き、行動し、結果と比較しましょう。','振り返りは、答えだけでなく考え方を改善する助けになります。','証拠、仮定、次の一歩を、短い意思決定ノートに記しましょう。','目標は確実性ではなく、よりよく学ぶ方法です。','今日は一つの問いから始め、十分に注意を向けてみましょう。'],
    es: ['Pensar con claridad es una habilidad que podemos practicar, no un talento innato.','Cuando abunda la información, prestar atención se convierte en una elección.','Una respuesta segura puede basarse en una suposición débil.','Antes de buscar una respuesta, dedica un momento a definir la pregunta.','¿Qué intentas comprender o decidir exactamente?','Escribe la pregunta con tus propias palabras, de la forma más sencilla posible.','Pensar con claridad empieza por separar lo que sabes de lo que supones.','Un hecho se puede comprobar. Una suposición aún necesita ponerse a prueba.','Ponlos en dos columnas y observa dónde faltan pruebas.','Por ejemplo, una idea popular no es necesariamente una idea útil.','Antes de buscar más apoyo, pregúntate qué te haría cambiar de opinión.','Este pequeño hábito crea espacio entre una reacción y una decisión.','Una buena pregunta hace visible tu incertidumbre.','Usa la IA para explorar alternativas, no solo para repetir tu primera idea.','Pide el argumento más sólido contra tu respuesta preferida.','Trata una respuesta de la IA como un punto de partida para investigar.','Rastrea una afirmación importante hasta su fuente original.','Si no puedes verificar una afirmación, conserva la incertidumbre en tus notas.','Convierte lo aprendido en un pequeño experimento que puedas hacer esta semana.','Escribe una predicción, actúa y compara el resultado.','La reflexión mejora tu forma de pensar, no solo la respuesta.','Lleva un breve diario de decisiones: pruebas, suposiciones y el siguiente paso.','El objetivo no es la certeza, sino aprender mejor.','Empieza hoy con una pregunta y préstale toda tu atención.'],
    fr: ['Penser clairement est une compétence qui se pratique, pas un talent inné.','Quand l’information abonde, notre attention devient un choix délibéré.','Une réponse assurée peut reposer sur une hypothèse fragile.','Avant de chercher une réponse, prenez le temps de définir la question.','Que cherchez-vous exactement à comprendre ou à décider ?','Écrivez la question avec vos propres mots, le plus simplement possible.','Penser clairement commence par distinguer ce que vous savez de ce que vous supposez.','Un fait peut être vérifié. Une hypothèse doit encore être testée.','Placez-les dans deux colonnes et repérez les preuves manquantes.','Par exemple, une idée populaire n’est pas forcément une idée utile.','Avant de chercher des confirmations, demandez-vous ce qui vous ferait changer d’avis.','Cette petite habitude crée un espace entre une réaction et une décision.','Une bonne question rend votre incertitude visible.','Utilisez l’IA pour explorer des alternatives, pas seulement pour répéter votre première idée.','Demandez le meilleur argument contre la réponse que vous préférez.','Considérez une réponse de l’IA comme le point de départ d’une recherche.','Remontez une affirmation importante jusqu’à sa source originale.','Si vous ne pouvez pas vérifier une affirmation, notez cette incertitude.','Transformez votre apprentissage en une petite expérience à réaliser cette semaine.','Écrivez une prédiction, agissez, puis comparez le résultat.','La réflexion améliore votre manière de penser, pas seulement la réponse.','Tenez un bref journal de décisions : preuves, hypothèses et prochaine étape.','Le but n’est pas la certitude, mais une meilleure façon d’apprendre.','Commencez aujourd’hui par une question et accordez-lui toute votre attention.']
  };
  const presets = {
    '深度学习': '请用简体中文总结整个视频，面向初学者。按「核心观点、解释、案例、实践步骤」组织，保留重要时间戳。最后给出 3 条可执行建议，并区分原文观点与补充解释。',
    '快速概览': '请用简体中文，用 300 字以内概括整个视频。提炼 3 个核心观点、一个最值得回看的片段，并保留时间戳。',
    '行动清单': '请将整个视频总结为一份可执行的行动清单。每条包含「要做什么、为什么、如何开始」，标注对应时间戳，避免泛泛的建议。'
  };
  let root, seek = () => {}, toast = () => {}, language = 'zh-CN', displayMode = 'bilingual', time = 92, currentTab = 'transcript', follow = true, query = '', activeIndex = -1, generating = false;
  let prompt = presets['深度学习'];
  try { prompt = localStorage.getItem('luma-demo-prompt') || prompt; } catch {}
  const esc = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stamp = seconds => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`;
  const $ = selector => root.querySelector(selector);
  const atTime = seconds => { let i = rows.findIndex((row, idx) => seconds >= row[0] && (!rows[idx + 1] || seconds < rows[idx + 1][0])); return i < 0 ? 0 : i; };
  function getCaption(seconds, code = language) { const i = atTime(seconds); return { en: rows[i][1], translated: code === 'en' ? rows[i][1] : translations[code]?.[i] || rows[i][2] }; }
  function summaryHTML() {
    return `<div class="lp-summary-intro"><span class="lp-demo-badge">演示总结</span><span class="lp-meta">基于原创示例内容</span></div>
      <h2 class="lp-summary-title">让 AI 成为思考伙伴，<br>保留自己的判断。</h2>
      <p class="lp-prose">清晰思考始于一个准确的问题。先分清事实和假设，再用 AI 探索不同视角；回到证据验证答案，最后把认知转化为行动。</p>
      <div class="lp-summary-stat"><span>6 个章节</span><span>3 个核心观点</span><span>约 2 分钟读完</span></div>
      <h3 class="lp-section-title">核心观点</h3>
      <article class="lp-idea"><div class="lp-idea-head"><span class="lp-idea-no">01</span><button class="lp-time-link" data-seek="92">01:32 ↗</button></div><h4>先把问题想清楚</h4><p>把已知事实和未经检验的假设分开。好的提问，会让缺少的证据变得具体。</p><div class="lp-takeaway">试试看：把你的问题改写成一句话。</div></article>
      <article class="lp-idea"><div class="lp-idea-head"><span class="lp-idea-no">02</span><button class="lp-time-link" data-seek="240">04:00 ↗</button></div><h4>让 AI 提供另一种视角</h4><p>主动寻找不同方案和反对意见。对重要论断追溯原始来源，并保留不确定性。</p><div class="lp-takeaway">试试看：请 AI 反驳你最倾向的答案。</div></article>
      <article class="lp-idea"><div class="lp-idea-head"><span class="lp-idea-no">03</span><button class="lp-time-link" data-seek="670">11:10 ↗</button></div><h4>用行动检验想法</h4><p>做一个足够小的实验，记录预测与结果。通过复盘，不断修正自己的思考方式。</p><div class="lp-takeaway">试试看：写下本周就能完成的一步。</div></article>
      <p class="lp-footnote">以上是界面演示文案，不是对参考视频的实际总结。</p>`;
  }
  function transcriptHTML() {
    return `<div class="lp-transcript-tools"><label class="lp-search"><span aria-hidden="true">⌕</span><input id="lp-search-input" type="search" placeholder="搜索字幕中的内容" aria-label="搜索字幕"></label><button class="lp-follow is-on" id="lp-follow-btn" aria-pressed="true" title="自动跟随当前字幕">跟随播放</button></div>
      <div class="lp-transcript-meta"><span>英语原文 <span class="lp-arrow">→</span> <span id="lp-target-label">简体中文</span></span><span id="lp-row-count">24 句示例</span></div><div id="lp-transcript" class="lp-transcript-list" aria-label="双语字幕列表"></div>`;
  }
  function mapHTML() {
    const branches = [
      ['定义问题', '01:32', 92, ['用一句话说清楚问题', '区分事实与假设', '找出缺少的证据']],
      ['拓展视角', '04:00', 240, ['用 AI 探索替代方案', '寻找最有力的反对意见']],
      ['验证信息', '07:00', 420, ['追溯原始来源', '记录尚未证实的部分']],
      ['付诸实践', '11:10', 670, ['设计一个小实验', '对照预测与结果', '定期复盘决策日志']]
    ];
    return `<div class="lp-map-toolbar"><div><span class="lp-demo-badge">演示导图</span><p>把知识串联起来</p></div><button class="lp-small-button" id="lp-map-toggle">全部收起</button></div><div id="lp-map" class="lp-map"><div class="lp-map-root">AI 时代的清晰思考<span>从提问，到行动</span></div><div class="lp-map-branches">${branches.map((b,i) => `<div class="lp-map-branch"><div class="lp-map-branch-head"><button class="lp-branch-toggle" aria-expanded="true" data-branch="${i}"><span class="lp-branch-symbol" aria-hidden="true">−</span>${b[0]}</button><button class="lp-time-link" data-seek="${b[2]}">${b[1]} ↗</button></div><ul id="lp-branch-${i}">${b[3].map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div></div><p class="lp-footnote">点击节点可展开或收起，点击时间可回看。<br>正式版将支持编辑节点与 XMind 下载。</p>`;
  }
  function chatHTML() {
    return `<div class="lp-chat-welcome"><span class="lp-chat-mark">AI</span><h2>和这个视频聊一聊</h2><p>把没听懂的地方，变成新的理解。</p><span class="lp-demo-badge">预设问答演示 · 未连接 AI</span></div><div class="lp-suggestions"><button data-question="这节课最重要的观点是什么？">这节课最重要的观点是什么？<span>↗</span></button><button data-question="如何区分事实和假设？">如何区分事实和假设？<span>↗</span></button><button data-question="给我一份今天就能实践的清单">给我一份今天就能实践的清单<span>↗</span></button></div><div id="lp-messages" class="lp-messages" aria-live="polite"></div><form class="lp-chat-form" id="lp-chat-form"><label class="lp-visually-hidden" for="lp-question">询问视频内容</label><textarea id="lp-question" placeholder="关于这个视频，你想了解什么？" rows="2" maxlength="500"></textarea><div><span>回答将附上视频时间点</span><button type="submit" class="lp-send" aria-label="发送问题">↑</button></div></form>`;
  }
  function renderRows() {
    const visible = rows.map((r,i) => ({r,i,tr:getCaption(r[0]).translated})).filter(({r,tr}) => !query || `${r[1]} ${tr}`.toLowerCase().includes(query.toLowerCase()));
    $('#lp-row-count').textContent = query ? `${visible.length} 个结果` : '24 句示例';
    $('#lp-transcript').innerHTML = visible.length ? visible.map(({r,i,tr}) => `<button class="lp-caption-row ${i===atTime(time)?'is-active':''}" data-seek="${r[0]}" data-caption-index="${i}" ${i===atTime(time)?'aria-current="true"':''}><span class="lp-caption-top"><time>${stamp(r[0])}</time><span class="lp-playing-label">当前句</span></span>${displayMode!=='translated'||language==='en'?`<span class="lp-caption-en">${esc(r[1])}</span>`:''}${language==='en'||displayMode==='original'?'':`<span class="lp-caption-translation">${esc(tr)}</span>`}</button>`).join('') : '<div class="lp-empty"><strong>没有找到相关字幕</strong><p>试试 “AI”、“事实” 或 “question”。</p><button class="lp-small-button" id="lp-clear-search">清空搜索</button></div>';
    activeIndex = atTime(time);
  }
  function setFollow(value) { follow = value; $('#lp-follow-btn').classList.toggle('is-on', follow); $('#lp-follow-btn').setAttribute('aria-pressed', String(follow)); $('#lp-follow-btn').textContent = follow ? '跟随播放' : '恢复跟随'; }
  function scrollActive(behavior = 'smooth') { const list = $('#lp-transcript'), item = list.querySelector('.is-active'); if(item && list.clientHeight) list.scrollTo({ top: Math.max(0, item.getBoundingClientRect().top - list.getBoundingClientRect().top + list.scrollTop - list.clientHeight / 3), behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : behavior }); }
  function updateTime(seconds) { time = seconds; if (!root) return; const index = atTime(seconds); if(index !== activeIndex){ root.querySelectorAll('[data-caption-index]').forEach(el=>{const active=Number(el.dataset.captionIndex)===index;el.classList.toggle('is-active',active); if(active) el.setAttribute('aria-current','true');else el.removeAttribute('aria-current');}); activeIndex=index; if(follow && currentTab==='transcript') scrollActive(); } }
  function setLanguage(code) { language = ['zh-CN','ja','es','fr','en'].includes(code) ? code : 'zh-CN'; if(!root)return; $('#lp-target-label').textContent = {'zh-CN':'简体中文',ja:'日本語',es:'Español',fr:'Français',en:'仅英语'}[language]; renderRows(); if(follow) scrollActive('instant'); }
  function setDisplayMode(mode) { displayMode = ['bilingual','original','translated'].includes(mode) ? mode : 'bilingual'; if(!root)return; renderRows(); if(follow) scrollActive('instant'); }
  function showTab(tab) { tab = ({subtitles:'transcript',mindmap:'map',qa:'chat',question:'chat'})[tab] || tab; if(!['transcript','summary','map','chat'].includes(tab)) return; currentTab = tab; root.querySelectorAll('[data-tab]').forEach(el=>{ const active=el.dataset.tab===tab;el.classList.toggle('is-active',active);el.setAttribute('aria-selected', String(active));el.tabIndex=active?0:-1; });root.querySelectorAll('[data-panel]').forEach(el=>{el.hidden=el.dataset.panel!==tab;}); if(tab==='transcript'&&follow) requestAnimationFrame(()=>scrollActive('instant')); closeExport(); }
  function openPrompt() { $('#lp-prompt-text').value = prompt; $('#lp-prompt-dialog').showModal(); }
  function closeExport() { $('#lp-export-menu').hidden=true;$('#lp-export-btn').setAttribute('aria-expanded','false'); }
  function openExport() { const menu=$('#lp-export-menu');menu.hidden=!menu.hidden;$('#lp-export-btn').setAttribute('aria-expanded',String(!menu.hidden)); if(!menu.hidden)menu.querySelector('button').focus(); }
  function markdown() { return `# AI 时代的清晰思考\n\n> 界面演示：以下为原创示例内容，不是参考视频的实际总结。\n\n## 一句话总结\n先分清事实和假设，再用 AI 探索不同视角；回到证据验证答案，最后把认知转化为行动。\n\n## 核心观点\n### 01:32 先把问题想清楚\n把已知事实和未经检验的假设分开。用一句话说清楚你的问题。\n\n### 04:00 让 AI 提供另一种视角\n主动寻找不同方案和反对意见，对重要论断追溯原始来源。\n\n### 11:10 用行动检验想法\n做一个足够小的实验，记录预测与结果，通过复盘修正思考方式。\n\n## 当前保存的 Prompt（本演示未调用模型）\n${prompt}\n`; }
  function exportMD() {const url=URL.createObjectURL(new Blob(['\uFEFF',markdown()],{type:'text/markdown;charset=utf-8'})); const a=document.createElement('a');a.href=url;a.download='清晰思考-演示学习笔记.md';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);closeExport();toast('已发起示例 Markdown 下载');}
  function printPDF() {closeExport();let print=document.getElementById('print-summary');if(!print){print=document.createElement('section');print.id='print-summary';document.body.append(print);}print.innerHTML=`<h1>AI 时代的清晰思考</h1><p>学习笔记 · 原创示例内容 · 交互原型</p>${summaryHTML()}<h3>当前保存的总结 Prompt</h3><p>${esc(prompt)}</p>`; window.print(); }
  function ask(question) {question=question.trim();if(!question)return;$('#lp-question').value='';const specific=/事实|假设/.test(question), action=/清单|实践|行动/.test(question); const answer=specific?'可以先把一个判断拆成两列：「可以核查的证据」和「尚待验证的假设」。例如，“这段视频有 24 条评论”可以核查；“评论多，所以观点一定正确”则是需要验证的假设。':action?'今天可以完成三步：① 用一句话写下你想解决的问题；② 分列事实与假设，请 AI 提供一个相反视角；③ 选择一个最小行动，写下预测，明天对照结果。':'这节课的示例观点是：用 AI 帮你拓展思路，同时保留自己的判断。先定义问题，再检查证据，最后通过小实验验证想法。'; const seconds=action?670:92; const container=$('#lp-messages');const message=document.createElement('div');message.innerHTML=`<div class="lp-user-message">${esc(question)}</div><div class="lp-ai-message"><div><span class="lp-ai-avatar">AI</span><span class="lp-demo-badge">演示回答</span></div><p>${answer}</p><button class="lp-citation" data-seek="${seconds}">${stamp(seconds)} · ${action?'用行动检验想法':'区分事实与假设'} ↗</button><small>这是预设回答，用于验证问答与回看流程。</small></div>`;container.append(message); $('.lp-chat-welcome').hidden=true;$('.lp-suggestions').hidden=true; message.scrollIntoView({block:'nearest',behavior:'smooth'});}
  function init(options) {
    root=options.root;seek=options.seek||seek;toast=options.toast||toast;root.classList.add('lp-root');
    root.innerHTML=`<div class="lp-panel-heading"><div><span class="lp-heading-mark">s.</span><strong>学习空间</strong></div><span class="lp-heading-note">示例课程</span></div>
      <nav class="lp-tabs" id="lp-tabs" role="tablist" aria-label="学习功能">${[['transcript','字幕'],['summary','AI 总结'],['map','思维导图'],['chat','AI 问答']].map(([id,label])=>`<button role="tab" id="lp-tab-${id}" class="${id==='transcript'?'is-active':''}" data-tab="${id}" aria-controls="lp-view-${id}" aria-selected="${id==='transcript'}" tabindex="${id==='transcript'?0:-1}">${label}${id==='transcript'?'<span class="lp-tab-count">24</span>':''}</button>`).join('')}</nav>
      <section class="lp-view lp-transcript-view" data-panel="transcript" id="lp-view-transcript" role="tabpanel" aria-labelledby="lp-tab-transcript">${transcriptHTML()}</section>
      <section class="lp-view" data-panel="summary" id="lp-view-summary" role="tabpanel" aria-labelledby="lp-tab-summary" hidden><div class="lp-summary-tools"><span>视频精华，一眼掌握</span><button class="lp-small-button" id="lp-prompt-btn">自定义 Prompt</button></div><div class="lp-summary-scroll"><div id="lp-summary-content">${summaryHTML()}</div><button id="lp-generate-btn" class="lp-generate">重新生成总结 <span>↻</span></button><p class="lp-footnote lp-centered">演示生成流程，不消耗 AI 额度</p></div></section>
      <section class="lp-view lp-map-view" data-panel="map" id="lp-view-map" role="tabpanel" aria-labelledby="lp-tab-map" hidden>${mapHTML()}</section>
      <section class="lp-view lp-chat-view" data-panel="chat" id="lp-view-chat" role="tabpanel" aria-labelledby="lp-tab-chat" hidden>${chatHTML()}</section>
      <footer class="lp-footer"><div class="lp-export-menu" id="lp-export-menu" hidden><div class="lp-menu-caption">导出这份演示笔记</div><button data-export="pdf"><span class="lp-file-type">PDF</span><span>排版文档<small>打开打印窗口，另存为 PDF</small></span></button><button data-export="md"><span class="lp-file-type">MD</span><span>Markdown<small>下载可编辑的示例文本</small></span></button><button data-export="xmind"><span class="lp-file-type">XM</span><span>XMind 思维导图<small>预览导出设置 · 尚未接入</small></span></button></div><span class="lp-footer-note">把灵感，带走。</span><button class="lp-export-button" id="lp-export-btn" aria-expanded="false" aria-controls="lp-export-menu">导出笔记 <span aria-hidden="true">↓</span></button></footer>
      <dialog class="lp-dialog" id="lp-prompt-dialog" aria-labelledby="lp-prompt-title"><div class="lp-dialog-head"><div><span class="lp-dialog-eyebrow">让总结更懂你</span><h2 id="lp-prompt-title">自定义总结 Prompt</h2></div><button class="lp-close" data-close="lp-prompt-dialog" aria-label="关闭提示词设置">×</button></div><p class="lp-dialog-intro">选择一个起点，再告诉 AI 你想如何理解这个视频。</p><div class="lp-preset-buttons">${Object.keys(presets).map(x=>`<button data-preset="${x}">${x}</button>`).join('')}</div><label class="lp-field-label" for="lp-prompt-text">你的总结要求</label><textarea id="lp-prompt-text" rows="7" maxlength="4000"></textarea><p class="lp-dialog-hint">正式版支持输出语言、详细程度和关注主题。当前仅在本机保存，不调用 AI。</p><div class="lp-dialog-actions"><button class="lp-small-button" id="lp-reset-prompt">恢复默认</button><button class="lp-primary" id="lp-save-prompt">保存 Prompt</button></div></dialog>
      <dialog class="lp-dialog" id="lp-xmind-dialog" aria-labelledby="lp-xmind-title"><div class="lp-dialog-head"><div><span class="lp-dialog-eyebrow">带走一张知识地图</span><h2 id="lp-xmind-title">导出 XMind</h2></div><button class="lp-close" data-close="lp-xmind-dialog" aria-label="关闭 XMind 设置">×</button></div><p class="lp-dialog-intro">预览正式版的导出设置。</p><label class="lp-field-label" for="lp-xmind-layout">导图布局</label><select id="lp-xmind-layout"><option value="tree">向右展开的树状图</option><option value="mind">居中发散的思维导图</option></select><label class="lp-checkbox"><input type="checkbox" id="lp-xmind-time" checked> 保留章节时间戳</label><div class="lp-xmind-preview"><strong>AI 时代的清晰思考</strong><p id="lp-xmind-preview-text">树状图 · 4 个分支 · 包含时间戳</p></div><p class="lp-dialog-hint">演示版暂不生成 .xmind 文件。正式开发后可下载并在 XMind 中继续编辑。</p><div class="lp-dialog-actions"><span></span><button class="lp-primary" data-close="lp-xmind-dialog">完成预览</button></div></dialog>`;
    renderRows();
    root.addEventListener('click', event=>{
      const button=event.target.closest('button');if(!button)return;
      if(button.dataset.tab)showTab(button.dataset.tab);
      if(button.dataset.seek!==undefined){const seconds=Number(button.dataset.seek);seek(seconds);updateTime(seconds);}
      if(button.dataset.close)$('#'+button.dataset.close).close();
      if(button.dataset.preset){$('#lp-prompt-text').value=presets[button.dataset.preset];root.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('is-selected',x===button));}
      if(button.dataset.question)ask(button.dataset.question);
      if(button.dataset.branch!==undefined){const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));button.querySelector('.lp-branch-symbol').textContent=expanded?'+':'−';$('#lp-branch-'+button.dataset.branch).hidden=expanded;$('#lp-map-toggle').textContent=root.querySelectorAll('[data-branch][aria-expanded="true"]').length?'全部收起':'全部展开';}
      if(button.dataset.export==='md')exportMD();if(button.dataset.export==='pdf')printPDF();if(button.dataset.export==='xmind'){closeExport();$('#lp-xmind-dialog').showModal();}
      if(button.id==='lp-clear-search'){$('#lp-search-input').value='';query='';renderRows();}
    });
    $('#lp-tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const tabs=[...$('#lp-tabs').querySelectorAll('[data-tab]')];let idx=tabs.findIndex(x=>x===document.activeElement);if(idx<0)return;event.preventDefault();idx=event.key==='Home'?0:event.key==='End'?3:(idx+(event.key==='ArrowRight'?1:-1)+4)%4;showTab(tabs[idx].dataset.tab);tabs[idx].focus();});
    $('#lp-search-input').addEventListener('input',event=>{query=event.target.value;setFollow(!query);renderRows();if(!query)scrollActive();});
    $('#lp-follow-btn').addEventListener('click',()=>{setFollow(!follow);if(follow){query='';$('#lp-search-input').value='';renderRows();scrollActive();}});
    $('#lp-transcript').addEventListener('wheel',()=>setFollow(false),{passive:true});$('#lp-transcript').addEventListener('touchmove',()=>setFollow(false),{passive:true});
    $('#lp-prompt-btn').addEventListener('click',openPrompt);$('#lp-reset-prompt').addEventListener('click',()=>{$('#lp-prompt-text').value=presets['深度学习'];});
    $('#lp-save-prompt').addEventListener('click',()=>{const value=$('#lp-prompt-text').value.trim();if(!value){$('#lp-prompt-text').focus();toast('请先填写总结要求');return;}prompt=value;let persisted=true;try{localStorage.setItem('luma-demo-prompt',prompt);}catch{persisted=false;}$('#lp-prompt-dialog').close();toast(persisted?'Prompt 已保存在本机；演示版未连接 AI':'Prompt 已暂存于本次页面；浏览器禁用了本地存储');});
    $('#lp-generate-btn').addEventListener('click',()=>{if(generating)return;generating=true;const btn=$('#lp-generate-btn');btn.disabled=true;btn.innerHTML='<span class="lp-spinner"></span> 正在整理示例内容…';$('#lp-summary-content').classList.add('lp-is-loading');setTimeout(()=>{generating=false;btn.disabled=false;btn.innerHTML='重新生成总结 <span>↻</span>';$('#lp-summary-content').classList.remove('lp-is-loading');toast('演示生成完成；正式版将根据你的 Prompt 调用 AI');},1400);});
    $('#lp-map-toggle').addEventListener('click',()=>{const expand=!root.querySelector('[data-branch][aria-expanded="true"]');root.querySelectorAll('[data-branch]').forEach(btn=>{btn.setAttribute('aria-expanded',String(expand));btn.querySelector('.lp-branch-symbol').textContent=expand?'−':'+';$('#lp-branch-'+btn.dataset.branch).hidden=!expand;});$('#lp-map-toggle').textContent=expand?'全部收起':'全部展开';});
    $('#lp-chat-form').addEventListener('submit',event=>{event.preventDefault();ask($('#lp-question').value);});$('#lp-question').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();ask(event.target.value);}});
    $('#lp-export-btn').addEventListener('click',openExport);document.addEventListener('click',event=>{if(!$('#lp-export-menu').hidden&&!event.target.closest('.lp-footer'))closeExport();});root.addEventListener('keydown',event=>{if(event.key==='Escape')closeExport();});
    const updatePreview=()=>{$('#lp-xmind-preview-text').textContent=`${$('#lp-xmind-layout').value==='tree'?'树状图':'思维导图'} · 4 个分支 · ${$('#lp-xmind-time').checked?'包含':'不含'}时间戳`;};$('#lp-xmind-layout').addEventListener('change',updatePreview);$('#lp-xmind-time').addEventListener('change',updatePreview);
    root.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
    requestAnimationFrame(()=>scrollActive('instant'));
  }
  window.LearningPanel={init,updateTime,setLanguage,setDisplayMode,showTab,openPrompt,openExport,getCaption};
})();
